## cartridge.properties for cartridge commerce_assets
demandware.cartridges.commerce_assets.multipleLanguageStorefront=true
demandware.cartridges.commerce_assets.id=commerce_assets
demandware.cartridges.commerce_assets.version=0.0.1
