## cartridge.properties for cartridge commerce_layouts
demandware.cartridges.commerce_layouts.multipleLanguageStorefront=true
demandware.cartridges.commerce_layouts.id=commerce_layouts
demandware.cartridges.commerce_layouts.version=0.0.1
